CXX = g++
CXXFLAGS = -std = c++11 - Wall - Wextra - pedantic
LDLIBS =

SRCS = htable.h test.cpp
OBJS = $(SRCS:.cpp = .o)

all: test

test : $(OBJS)
$(CXX) $(CXXFLAGS) $(LDFLAGS) - o $@ $ ^ $(LDLIBS)

% .o: % .cpp
$(CXX) $(CXXFLAGS) - c $ < -o $@

	clean :
	rm - f * .o test
